// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Pt_kCO69o-LnwC-QbLaulgyU9wm2K3I',
    appId: '1:997091365239:web:2ac4454bb0647c37841172',
    messagingSenderId: '997091365239',
    projectId: 'teste-firebase-fe962',
    authDomain: 'teste-firebase-fe962.firebaseapp.com',
    storageBucket: 'teste-firebase-fe962.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxit-yTaLTWvVGwcgSZUZlmNvijsW1AE',
    appId: '1:997091365239:android:dc1a7357d3bfee37841172',
    messagingSenderId: '997091365239',
    projectId: 'teste-firebase-fe962',
    storageBucket: 'teste-firebase-fe962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-C6hssLwqv5QBzZmI2XybdNMx3XD8OI',
    appId: '1:997091365239:ios:f99470e69013891d841172',
    messagingSenderId: '997091365239',
    projectId: 'teste-firebase-fe962',
    storageBucket: 'teste-firebase-fe962.appspot.com',
    iosBundleId: 'com.bearerbyte.appDeSaude',
  );
}
